src/Ataoge.SsoServer.Web/Models/RedirectViewModel.cs
namespace Ataoge.SsoServer.Web.Models
{
    public class RedirectViewModel
    {
        public string RedirectUrl { get; set; }
    }
}

src/Ataoge.SsoServer.Web/ViewComponents/NavbarViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Ataoge.SsoServer.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ataoge.SsoServer.Web.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly IAuthorizationService _authorizationService;

        public NavbarViewComponent(IAuthorizationService authorizationService)
        {
            this._authorizationService = authorizationService;
        }

        public IViewComponentResult Invoke()
        {
            var menus = new List<MenuItem>();
            //menus.Add(new MenuItem() {Name = "首页", Url = "Index"});
            //menus.Add(new MenuItem() {Name = "隐私", Url = "Privacy"});

            if (User.Identity.IsAuthenticated)
            {
                menus.Add(new MenuItem() {Name = "关于", Url =  Url.Action("Index", "Home")});
            }

            if (User.IsInRole("admin"))
            {
                menus.Add(new MenuItem() {Name = "在线用户", Url = Url.Action("Online", "User")});
            }
            
            
            return View("Default", menus);
        }
    }
}

src/Ataoge.SsoServer.Web/Views/Shared/Redirect.cshtml
@model RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

src/Ataoge.SsoServer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 城信统一认证中心</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/open-iconic/font/css/open-iconic-bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>城信</b>统一认证中心</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @await Component.InvokeAsync("Navbar")
                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - 广州城市信息研究所有限公司 - <a asp-area="" asp-controller="Home" asp-action="Privacy">隐私政策</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Ataoge.SsoServer.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 城信统一认证中心</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/icomoon/style.css" />
    <link rel="stylesheet" href="~/css/login.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="skew-title" asp-area="" asp-controller="Home" asp-action="Index"><strong>城信</strong>统一认证中心</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    
                     <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="~/.well-known/openid-configuration">帮助文档</a>
                    </li>
                </ul>

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link">|</a>
                    </li>
                    <li class="nav-item"></li>
                    <span class="navbar-text">
                            登录
                        </span>
                    </li>
                </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2020 - 广州城市信息研究所有限公司 - <a asp-area="" asp-controller="Home" asp-action="Privacy">隐私政策</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Ataoge.SsoServer.Web/Views/Shared/_NavbarPartial.cshtml
<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">隐私</a>
                        </li>
                    </ul>

src/Ataoge.SsoServer.Web/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}